---
title       : Planning Income and Expenditure for Retirement
subtitle    : Course Project - Shiny Application and Reproducible Pitch
author      : Jonathan Mallia
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

---

## Objective

This is part of developing data products assignment from coursera.

The project consists in two activities:

> Create a Shiny application : The application is an Income and Retirement Planning created using Shiny. It is based on the idea by Pierre Chretien. 

> Create a presentation in Slidify or Rstudio Presenter to pitch for the application.

--- .class #id 

## Slide with code

This is a slide with some R code 

```{r }
summary(mtcars)
```

---

## Building the app

> I used an existing application, the idea created by Pierre Chretien, updated by Michael Kapler, and then Lin Crampton. 
    Source at https://github.com/lincrampton/time2retire
Pierre Chretien (https://lincrampton.shinyapps.io/time2retire/)  

> I enhanced the application by applying the concept to the local scenario. I also created the output in ggplot, and then transformed to Plotly.

> Please have a look at the application at : https://jonimatix.shinyapps.io/retirement_planning_app/ 

---

## Thank you!

Thanks for your attention!